apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesactive
  namespace: team1
spec:
  selector:
    matchLabels:
      app: salesactive
      version: v1
  template:
    metadata:
      labels:
        app: salesactive
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - image: chump1/sellers:salesactive-1
          name: salesactive
          hostname: salesactive
          ports:
            - containerPort: 8080
